Repository loot/skyrimse, pull requests merged in 2018-11, with the labels that each got.

#428 LOTD Moon & Star patch - Sort after MAS Immersion Patch
  masterlist.yaml
Labels: Metadata Update

#429 LOTD - WACCF Patch - Sorting Rules
  masterlist.yaml
Labels: Metadata Update

#430 Relic Hunter - Update Cleaning Info (Clean)
  masterlist.yaml
Labels: Metadata Update

#432 Rigmor of Bruma - Sorting Rules & Cleaning Info
  masterlist.yaml
Labels: Metadata Update

#437 Convenient Horses: Add 'Do Not Clean' warning
  masterlist.yaml
Labels: Corrections, Metadata Update

#438 Rigmor of Bruma - Sorting Rules & Cleaning Info (#432)
  masterlist.yaml
Labels: Metadata Update

#445 Early groups
  masterlist.yaml
Labels: Refactoring

#446 (Incompatible) Legacy of the Dragonborn & Unlimited Bookshelves
  masterlist.yaml
Labels: Metadata Update

#449 Audio Mod Updates
  masterlist.yaml
Labels: Metadata New, Metadata Update

#450 Landscape Fixes for Grass Mods - Sorting Rules Change
  masterlist.yaml
Labels: Metadata Update, sorting error

#453 Change Touring Carriages Group to addonsGroup
  masterlist.yaml
Labels: sorting error

#455 Replace Light Master Group with Fixes & Resources Group
  masterlist.yaml
Labels: Metadata Update

#456 Update Early loading groups
  masterlist.yaml
Labels: Metadata Update, Refactoring

#461 Corrections & Refactoring
  masterlist.yaml
Labels: Corrections, Refactoring

#464 Refactor Patch Included Message
  masterlist.yaml
Labels: Refactoring

#465 Add Common entry for 3rd party patches
  masterlist.yaml
Labels: Refactoring, enhancement

#468 Message Corrections & Refactoring
  masterlist.yaml
Labels: Corrections, Refactoring

#469 Updates for Palaces and castles
  masterlist.yaml
Labels: Metadata Update

#474 Falkreath - Add Required Sorting Rules
  masterlist.yaml
Labels: Metadata New

#475 Replace Group assigments using string with Alias
  masterlist.yaml
Labels: Corrections

#476 Update RS Children + CRF Patch ESP
  masterlist.yaml
Labels: Corrections, Metadata Update

#477 Updates for Landscape Fixes For Grass Mods
  masterlist.yaml
Labels: Metadata Update

#478 Arthmoor's mods - Update Cleaning Info
  masterlist.yaml
Labels: Metadata Update

#479 Refactor Groups
  masterlist.yaml
Labels: Metadata Update, Refactoring

#480 Refactor - Remove Mod Specific Groups (#479)
  masterlist.yaml
Labels: Refactoring, enhancement

#482 Imperious - Incompatible plugins
  masterlist.yaml
Labels: Metadata Update

#484 Rebalanced Encounter Zones - Sorting Rules & Use Only One Version
  masterlist.yaml
Labels: Metadata New

#485 Better Dynamic Majestic Mountains
  masterlist.yaml
Labels: Metadata New, Metadata Update

#486 Add Swift Potions Reborn
  masterlist.yaml
Labels: Metadata New

#490 RealisticWaterTwo Updates
  masterlist.yaml
Labels: Metadata Update, Refactoring
