Repository loot/skyrimse, pull requests merged in 2018-06, with the labels that each got.

#155 Arthmoors mods[No Villages] - Update existing and add missing mods
  masterlist.yaml
Labels: Metadata Update

#157 Merge v0.13 updates to v0.10
  masterlist.yaml
Labels: awaiting-feedback

#158 RDO - Update load after rules - Add Compatibilty checks & Cleaning info
  masterlist.yaml
Labels: Metadata Update

#160 Immersive Citizens Update Rules & Compatibility
  masterlist.yaml
Labels: Metadata Update

#161 [Meta Data] Beyond Skyrim Bruma - Update Cleaning Info
  masterlist.yaml
Labels: Metadata Update

#162 Update - Default Groups
  masterlist.yaml
Labels: Metadata Update

#163 New Mods added & Update Cleaning info
  masterlist.yaml
Labels: Metadata Update

#164 Morrowloot Ultimate Update - Patch checks & cleaning info
  masterlist.yaml
Labels: Metadata Update

#165 Add check for merged patch to MLU patch conditionals
  masterlist.yaml
Labels: Metadata Update

#166 Audio Overhauls - New Entries Updates
  masterlist.yaml
Labels: Metadata Update

#167 Update for Reverb and Ambiance Overhaul
  masterlist.yaml
Labels: Metadata Update

#169 New entry - Whiterun Hold Forest, Update Touring Carriages
  masterlist.yaml
Labels: Metadata Update

#170 Immersive Citizens - Update Compatibility Notes & patch groups
  masterlist.yaml
Labels: Metadata Update

#171 Update Patch message for The People of Skyrim ICAIO PATCH
  masterlist.yaml
Labels: Metadata Update

#172 Fix incorrect link - RSChildren - CRF Patch
  masterlist.yaml
Labels: Metadata Update

#173 New Entries - Proud spire manor home mods - Dirty plug-ins
  masterlist.yaml
Labels: Metadata Update

#174 Immersive Citizens - Load after rules Updated
  masterlist.yaml
Labels: Metadata Update

#176 Bells of Skyrim - OCS+ICAIO Patch cyclic fix
  masterlist.yaml
Labels: Metadata Update

#179 LoS+BsBruma cyclic fix, SoS crc+patch inc & RAO patch checks.
  masterlist.yaml
Labels: Metadata Update

#180 [New Groups] Realistic Water & Enhanced Lighting
  masterlist.yaml
Labels: Metadata Update

#181 [New Groups] Core Mod Groups
  masterlist.yaml
Labels: Metadata Update

#183 Update - Alt Start load after rules
  masterlist.yaml
Labels: Metadata Update

#187 Group Structure - Remove unnecessary load after rules.
  masterlist.yaml
Labels: Metadata Update

#196 Weather Mods & True Storms Compatibility Patches
  masterlist.yaml
Labels: Metadata New

#198 add 'Immersive College of Winterhold' to masterlist
  masterlist.yaml
Labels: Metadata New

#200 add 'Teleport - City Spells' to masterlist
  masterlist.yaml
Labels: Metadata New
