Repository loot/skyrimse, pull requests merged in 2018-10, with the labels that each got.

#353 Load Realistic High Altitude Treeline early
  masterlist.yaml
Labels: Metadata New

#354 USSEP - Remove Load after Gray Fox Cowl MajesticMountains_Landscape
  masterlist.yaml
Labels: Corrections

#355 Load Sacrosanct & Apocalypse after Ordinator
  masterlist.yaml
Labels: Metadata Update

#358 Sort Dawnstar after ICAIO & Landscape Fixes
  masterlist.yaml
Labels: Metadata New

#359 Hotfix
  masterlist.yaml
Labels: Metadata Update

#360 Updates
  masterlist.yaml
Labels: Metadata New, Metadata Update

#361 Update Requires SkyUI message
  masterlist.yaml
Labels: Corrections

#362 Sort Realistic Water Two after Open Cities
  masterlist.yaml
Labels: Metadata Update, sorting error

#363 Official/Unofficial Update Patches
  masterlist.yaml
Labels: Metadata New

#364 Joy of Perspective Compatibility Messages
  masterlist.yaml
Labels: Metadata New

#366 Cosmetic Vampire Overhaul
  masterlist.yaml
Labels: Metadata New

#367 Add Distinct Interiors - Sorting rules, Compatibility, Cleaning Info.
  masterlist.yaml
Labels: Metadata New

#368 Updates
  masterlist.yaml
Labels: Metadata New, Metadata Update

#370 Remove trailing whitespace
  masterlist.yaml
Labels: Corrections

#371 v1.5.53 Updates
  masterlist.yaml
Labels: Metadata Update

#373 Fix Scoped Bows Compatibility Kit Link
  masterlist.yaml
Labels: Corrections

#374 Add WACCF & Summermyst Enchantments Consistency Patch
  masterlist.yaml
Labels: Metadata New

#376 Refactor Require SkyUI & Do not Clean messages
  masterlist.yaml
Labels: Refactoring

#377 Cleanup Has Wild Edits message
  masterlist.yaml
Labels: Refactoring

#378 The Choice is yours Book Covers Patch
  masterlist.yaml
Labels: Metadata New, Metadata Update

#380 Add Economy Overhaul and Scarcity Patch to Lvllist Group
  masterlist.yaml
Labels: Metadata New

#385 Patch 7
  masterlist.yaml
Labels: Metadata New

#386 Lock Overhaul & Ordinator compatibility
  masterlist.yaml
Labels: Metadata New

#389 Falskaar fixes
  masterlist.yaml
Labels: Metadata New

#390 Falskaar - Addons and Patches
  masterlist.yaml
Labels: Metadata New

#391 Path of Sorcery - Sort after Ordinator
  masterlist.yaml
Labels: Metadata New

#392 Add Quick Clean message for latest xEdit.
  masterlist.yaml
Labels: enhancement

#394 Replaced all instances of tags: with tag:
  masterlist.yaml
Labels: Corrections, Metadata Update

#395 Audio Overhaul for Skyrim SE - ISC Synergy Patch
  masterlist.yaml
Labels: Metadata New

#396 Elianora Player Homes - Add/Update Cleaning info
  masterlist.yaml
Labels: Metadata New, Metadata Update

#398 Helarchen Creek
  masterlist.yaml
Labels: Metadata Update

#400 DLC - Quick Auto Cleaning Info
  masterlist.yaml
Labels: Metadata Update, enhancement

#401 Immersive Wenches & Cutting Room Floor Sorting
  masterlist.yaml
Labels: sorting error

#402 Use quick auto cleaning for BSHeartland.esm
  masterlist.yaml
Labels: Metadata Update

#403 Several improvements to the german localization in the masterlist
  masterlist.yaml
Labels: Corrections

#405 Enhanced Blood Textures and SkyBirds Compatibility Patch
  masterlist.yaml
Labels: Metadata Update

#406 Quick Auto Clean Updates
  masterlist.yaml
Labels: Metadata New

#408 Ultimate combat
  masterlist.yaml
Labels: Metadata New

#411 Cleaning info updates - USSEP, CRF, LOTD & Thunderchild
  masterlist.yaml
Labels: Metadata New, Metadata Update

#412 Guard Dialogue Overhaul - Updates
  masterlist.yaml
Labels: Metadata Update

#413 Randomized Word Walls - Dirty Plugin
  masterlist.yaml
Labels: Metadata New

#414 Unofficial Skyrim Special Edition Patch - Update Cleaning Info
  masterlist.yaml
Labels: Metadata Update

#407 Refactoring: Removed all unnecessary itm:, udr: and nav: entries
  masterlist.yaml
Labels: Refactoring

#417 Moon And Star - Sorting Rules & Cleaning Instructions
  masterlist.yaml
Labels: Metadata Update

#418 Undeath Remastered - Update Group & Cleaning Instructions
  masterlist.yaml
Labels: Metadata Update

#420 No Snow Under the Roof - Bug fixes & Cleaning Info
  masterlist.yaml
Labels: Metadata New

#422 The Brotherhood of Old
  masterlist.yaml
Labels: Metadata New

#423 Skyrim Sewers 4 - Add Cleaning Info (dirty)
  masterlist.yaml
Labels: Metadata New

#424 Tweaks
  masterlist.yaml
Labels: Corrections, Refactoring

#426 Dragons Keep - Add Cleaning Info (dirty)
  masterlist.yaml
Labels: Metadata New

#427 Skaal manor - Cleaning Info & Compatibility
  masterlist.yaml
Labels: Metadata New
