Repository loot/skyrimse, pull requests merged in 2018-08, with the labels that each got.

#266 [New] Weapons Armor Clothing & Clutter Fixes & Armor and Clothing Ext…
  masterlist.yaml
Labels: Metadata New

#270 Version updates (#269) Cleaning info & SkyUI Required message
  masterlist.yaml
Labels: Metadata Update, enhancement

#271 [Update] Add DLC Bash Tag suggestions
  masterlist.yaml
Labels: Metadata Update

#272 [NEW] Immersive Dawnguard Dayspring Pass
  masterlist.yaml
Labels: Metadata New

#273 [New] Dragon Bridge - Incompatible with DragonBridgeBoardwalk
  masterlist.yaml
Labels: Metadata New

#274 [new] Rorikstead - Incompatible with Rorikstead Revised
  masterlist.yaml
Labels: Metadata New

#275 [new] Mixwater Mill Reborn - Incompatible with Checkpoints of Skyrim
  masterlist.yaml
Labels: Metadata New

#276 [NEW] Whiterun Valley - Full & Lite versions
  masterlist.yaml
Labels: Metadata New

#277 V0.13 staging - Merge Updates
  masterlist.yaml
Labels: Metadata New, Metadata Update

#282 [New] Expanded Towns and Cities
  masterlist.yaml
Labels: Metadata New

#285 [NEW] Alternate Start -- New Beginnings
  masterlist.yaml
Labels: Metadata New

#287 Flag latest Verdant OCS version as being Incompatible with Open Cities.
  masterlist.yaml
Labels: Metadata Update

#288 Merge Updates - ETAC, Lighting Mods, ASLAL: NB & Verdant OCS
  masterlist.yaml
Labels: Metadata New, Metadata Update

#289 BandolierForNPC.esp added
  masterlist.yaml
Labels: Metadata New

#295 Add KS Dragon Overhaul
  masterlist.yaml
Labels: Metadata New

#296 Add Immersive Music
  masterlist.yaml
Labels: Metadata New

#297 Add Blended Roads
  masterlist.yaml
Labels: Metadata New

#298 Add Terrain LOD Redone
  masterlist.yaml
Labels: Metadata New

#299 Add Majestic Mountains
  masterlist.yaml
Labels: Metadata New

#300 Add Immersive Horses
  masterlist.yaml
Labels: Metadata New

#301 Add Race Menu
  masterlist.yaml
Labels: Metadata New

#302 Add Fores New Idles in Skyrim SE
  masterlist.yaml
Labels: Metadata New

#304 Add XP32 Maximum Skeleton
  masterlist.yaml
Labels: Metadata New

#306 Minor change - Replace Messages With Requires for XP32 Entry
  masterlist.yaml
Labels: Metadata Update

#305 Rebase Staging Commits To v0.13
  masterlist.yaml
Labels: Metadata New

#307 Add Toccata Follower SE & Elisif Replacer
  masterlist.yaml
Labels: Metadata New

#308 Remove Cell Bash Tags from Interesting NPCs Entry
  masterlist.yaml
Labels: Corrections, Metadata Update

#311 Add Lucidity Sound FX SSE
  masterlist.yaml
Labels: Metadata New

#312 Add Improved Hearthfire Lighting SE
  masterlist.yaml
Labels: Metadata New

#314 Bash tag Updates Book Covers & USSEP
  masterlist.yaml
Labels: Metadata Update

#316 Corrections For Patch Names ETAC Darkwater Crossing & JKs Skyrim
  masterlist.yaml
Labels: Corrections, Metadata Update

#317 Add Masters cleaning info for Latest Version
  masterlist.yaml
Labels: Metadata Update

#320 Add load after & incompatibility rules to WACCF
  masterlist.yaml
Labels: Metadata Update
