Repository loot/skyrimse, pull requests merged in 2018-07, with the labels that each got.

#206 add 'A Quality World Map' to masterlist
  masterlist.yaml
Labels: Metadata New

#208 Relighting Skyrim Update
  masterlist.yaml
Labels: Metadata Update

#209 Update some CRC to latest versions & Clean-up format of Cleaning info
  masterlist.yaml
Labels: Metadata Update

#210 Enhanced Lights and FX - Move to Overhauls Group & add info for its o…
  masterlist.yaml
Labels: Metadata New, Metadata Update

#212 Serana Dialogue Edit - Update Cleaning Info for latest version.
  masterlist.yaml
Labels: Metadata Update

#214 Corrections
  masterlist.yaml
Labels: Corrections

#215 Location updates
  masterlist.yaml
Labels: Metadata Update

#218 New Entry - Legacy of the Dragonborn
  masterlist.yaml
Labels: Metadata New

#221 LOTD compatibility patches masterlist update
  masterlist.yaml
Labels: Metadata New

#222 [New Entry] Unofficial High Definition Audio Project & [New Group] Li…
  masterlist.yaml
Labels: Metadata New

#223 [New Entry] Scarcity SE - Less Loot Mod
  masterlist.yaml
Labels: Metadata New

#224 LOTD Patch checks - Add check for Merged Patch to conditionals.
  masterlist.yaml
Labels: Corrections, Metadata Update

#226 [New] Heavy Armory
  masterlist.yaml
Labels: Metadata New

#228 Immersive weapons
  masterlist.yaml
Labels: Metadata New

#229 [New] Amulets of Skyrim
  masterlist.yaml
Labels: Metadata New

#231 [New] Skyrim Revamped - Complete Enemy Overhaul
  masterlist.yaml
Labels: Metadata New

#232 [New] Skyrim Revamped - Loot and Encounter Zones
  masterlist.yaml
Labels: Metadata New

#233 [New] InsanitySorrow Weapons Pack
  masterlist.yaml
Labels: Metadata New

#234 [New] Summermyst - Enchantments of Skyrim
  masterlist.yaml
Labels: Metadata New

#235 [New] Lore Weapon Expansion & Add-on Plug-ins
  masterlist.yaml
Labels: Metadata New

#236 [New] Cloaks of Skyrim
  masterlist.yaml
Labels: Metadata New

#237 [New] SkyTEST-RealisticAnimals&Predators
  masterlist.yaml
Labels: Metadata New

#238 [New] Wintermyst - Enchantments of Skyrim
  masterlist.yaml
Labels: Metadata New

#240 [New] Andromeda - Unique Standing Stones of Skyrim
  masterlist.yaml
Labels: Metadata New

#239 [Merge Updates] V0.13 dev masterlist
  masterlist.yaml
Labels: Metadata New, Metadata Update

#242 [New] Wildcat - Combat of Skyrim
  masterlist.yaml
Labels: Metadata New

#244 [New] Deadly Spell Impacts
  masterlist.yaml
Labels: Metadata New

#245 V0.13 Wildcat & Deadly Spell Impacts
  masterlist.yaml
Labels: Metadata New

#248 Updates for some of Arthmoors mods
  masterlist.yaml
Labels: Metadata Update

#250 V0.13 devmasterlist - Update Entries
  masterlist.yaml
Labels: Metadata Update

#256 [New] Skyrim Alchemy and Food Overhaul
  masterlist.yaml
Labels: Metadata New

#257 [New] Carriage Stops of Skyrim
  masterlist.yaml
Labels: Metadata New

#260 [New] SAFO & CSOS
  masterlist.yaml
Labels: Metadata New

#261 [Update] Load OCS after alt start
  masterlist.yaml
Labels: Metadata Update

#262 V0.13 staging - Merges Updates
  masterlist.yaml
Labels: Metadata New, Metadata Update
