Repository loot/skyrimse, pull requests merged in 2019-12, with the labels that each got.

#907 Updates for Smithing Perks Overhaul
  masterlist.yaml
Labels: correction, enhancement

#911 Updates for Kryptopyr's Patch Hub
  masterlist.yaml
Labels: enhancement, refactoring

#914 Add Distinct Interiors Fixes Replacer Plugins
  masterlist.yaml
Labels: correction, enhancement

#917 Add DynDOLOD.esm to Dynamic LOD group
  masterlist.yaml
Labels: enhancement

#921 Update SBCK patch messages
  masterlist.yaml
Labels: correction, refactoring

#933 Update CC plugin regex pattern
  masterlist.yaml
Labels: correction, refactoring

#943 Updates for True Storms Compatibility Patches
  masterlist.yaml
Labels: correction, refactoring

#945 Fixed the name of the Namira for good guys patch
  masterlist.yaml
Labels: correction

#946 Fixed using the wrong plugin name for two patches
  masterlist.yaml
Labels: correction
