Repository loot/skyrimse, pull requests merged in 2020-10, with the labels that each got.

#1336 Remove requirement from CBBE Morphs plugin
  masterlist.yaml
Labels: correction

#1350 Update Skyrim Landscape and Water Fixes
  masterlist.yaml
Labels: correction

#1356 Corrections for Invent.Remove and Relev changes made in #1341
  masterlist.yaml
Labels: correction

#1358 Update tags for Beasts of Tamriel
  masterlist.yaml
Labels: correction

#1394 Amend link for Triumvirate Compatibility Notes
  masterlist.yaml
Labels: correction

#1414 Update Water's Edge Fix
  masterlist.yaml
Labels: correction

#1416 Add common alias patchUnavailable
  masterlist.yaml
Labels: refactoring

#1465 Add common alias compatIssuesWithX
  masterlist.yaml
Labels: enhancement, refactoring

#1470 Update LotD Dawn of Skyrim patch message
  masterlist.yaml
Labels: correction
