Repository loot/skyrimse, pull requests merged in 2021-03, with the labels that each got.

#1642 Remove extra whitespaces
  masterlist.yaml
Labels: correction

#1648 Remove more extra whitespaces
  masterlist.yaml
Labels: correction

#1663 Replace &requiresSKSE
  masterlist.yaml
Labels: refactoring

#1664 Add Simplified Chinese &quickClean translation
  masterlist.yaml
Labels: localization

#1669 Update FNIS global message
  masterlist.yaml
Labels: refactoring

#1670 Update xSE Required Scripts global message
  masterlist.yaml
Labels: refactoring

#1673 Update global messages
  masterlist.yaml
Labels: refactoring

#1674 Add &runAnimFramework alias
  masterlist.yaml
Labels: refactoring

#1680 Remove Perks Unbound
  masterlist.yaml
Labels: refactoring

#1681 Add Bulgarian localization
  masterlist.yaml
Labels: localization

#1684 Update Korean localization
  masterlist.yaml
Labels: localization

#1685 Update aliased messages
  masterlist.yaml
Labels: correction

#1686 Update SKSE64 Plugin Requirements message
  masterlist.yaml
Labels: correction

#1687 Update Korean localization
  masterlist.yaml
Labels: localization

#1699 Update &moddingPlugin
  masterlist.yaml
Labels: localization

#1698 Added Swedish translation for &requiresResources
  masterlist.yaml
Labels: localization

#1707 Update &renameXtoY
  masterlist.yaml
Labels: localization

#1710 Add Italian localization
  masterlist.yaml
Labels: localization

#1717 Correct Portuguese locale codes
  masterlist.yaml
Labels: correction
