Repository loot/skyrimse, pull requests merged in 2021-04, with the labels that each got.

#1739 Update &patcherScriptAvailable
  masterlist.yaml
Labels: localization

#1747 Add &updateOcclusion
  masterlist.yaml
Labels: refactoring

#1749 Update to UCOW
  masterlist.yaml
Labels: correction

#1753 Update Wintersun - Faiths of Skyrim
  masterlist.yaml
Labels: correction, revisit

#1754 Update Scrambled Bugs
  masterlist.yaml
Labels: refactoring

#1785 Update Italian localization
  masterlist.yaml
Labels: localization
