Repository loot/skyrimse, pull requests merged in 2022-06, with the labels that each got.

#2416 Update A Quality World Map
  masterlist.yaml
Labels: correction, refactoring

#2417 Update Disease Descriptions for the Immersive Adventurer
  masterlist.yaml
Labels: refactoring

#2425 Update SunHelm Survival
  masterlist.yaml
Labels: correction

#2435 Update Cutting Room Floor
  masterlist.yaml
Labels: correction
